# IBM Carbon Gray 100 (dark) theme, from the /carbon-streamlit template, dark variant
[theme]
base = "dark"
primaryColor = "#0f62fe"
backgroundColor = "#161616"
secondaryBackgroundColor = "#262626"
textColor = "#f4f4f4"
font = "sans serif"

[server]
headless = true
runOnSave = true
